### ISSUE TITLE
sql_id.sql throws sqlplus-error

### ISSUE THREAD

**Issue by nklamann** [tanelpoder/tpt-oracle#13]
Due to wrong Column Header. This should be enclosed in ". I can provide a pull request

**Comment by tanelpoder** [comment]
Please do. Which version are you using, sqlid.sql doesn't throw errors in my env ...

**Comment by tanelpoder** [comment]
I mean which sqlplus version (I assume there's a sqlplus error, not DB error)

**Comment by nklamann** [comment]
SQLDveleoper 19.x , it wasa column CH#

**Comment by nklamann** [comment]
I created PR #14 for this

**Comment by tanelpoder** [comment]
Ok so it wasn't a sqlplus error, but SQL Developer error. Yep I've found SQL Developer not liking # in the column names for some reason (should actually raise this with SQL Dev dev team, they're quick to fix things). Thanks for the PR!

**Comment by nklamann** [comment]
I created  SR 3-21464161261 for this

**Comment by tanelpoder** [comment]
Thanks!

**Comment by nklamann** [comment]
Following bug has been created.Bug 30531514 - SP2-0158: UNKNOWN COLUMN OPTION WHEN USING SPECIAL CHARACTER FOR COLUMN HEADING AT SQL DEVELOPER WORKSHEET
--
