### ISSUE TITLE
Have you a new version  of snapper  script compatible with 19.6 Oracle.

### ISSUE THREAD

**Issue by Eddy-ml** [tanelpoder/tpt-oracle#24]
Hi Tanel,
I am very happy to register on your site, I have already attended your seminar at Paris SCGIB 2016. and I often read your news and your good scripts :).

Please, I have an issue with  snapper script  on oracle veriosn 19.6

 @snapper.sql ash 5 1 144

Sampling SID 144 with interval 5 seconds, taking 1 snapshots...
     and   s.why0+s.why1+s.why2 > 0
                         *
ORA-06550: line 905, column 26:
PL/SQL: ORA-00904: "S"."WHY2": invalid identifier
ORA-06550: line 842, column 9:
PL/SQL: SQL Statement ignored
Please   there is the version of snapper that i used: 
-- File name:   snapper.sql (Oracle Session Snapper v4).
Please, Do you   have a version  of snapper  script compatible with 19.6 Oracle.?

Thank you in advance.
Mehdi LISSIR

**Comment by tanelpoder** [comment]
Looks like you have an old version of Snapper, try with the latest version, it works on 19c (I've ran it on Oracle 19c up to 19.7)

**Comment by Eddy-ml** [comment]
Hi Tanel,
indeed, I downloaded the right version, it works very well. thank you very much.
Regards,
Mehdi LISSIR
