### ISSUE TITLE
Error while running snapper

### ISSUE THREAD

**Issue by prasanna108** [tanelpoder/tpt-oracle#5]
Hi Tanel,

I am getting below error while running the snapper code snippet.

could you please help me out
error:
Sampling SID 2161 with interval 1 seconds, taking 1 snapshots...

Error starting at line : 456 File @ H:\awr\snapper.sql
In command -
declare
    -- Snapper start
    -- forward declarations
    procedure output(p_txt in varchar2);
    procedure fout;
.
.
.
.

**Comment by tanelpoder** [comment]
Hi Prasanna,

A few questions:

1) Can yu paste the exect command line how you ran snapper
2) Are you running this within sqlplus or SQL Developer?
3) Did you download the script with "save as..." or used copy & paste to a .sql file? Often such errors show up when copy & paste messes up the script contents. 

If you used copy & paste, please try downloading or cloning the script with git and try again? If you still have a problem, please run snapper like this and paste the full output:

`@snapper all 5 1 lgwr`

Thanks,
Tanel.

**Comment by prasanna108** [comment]
Hi Tanel,

Sorry to respond very late. 
I have not raised the error message. 
I think someone else has got that error message.
Could you please cross check?

Thank you,
Prasanna

**Comment by tanelpoder** [comment]
Sorry I don't understand what to cross-check, did you not create this issue above?

**Comment by prasanna108** [comment]
No Tanel. I did not create this issue.
