### ISSUE TITLE
ORA-06550 running snapper.sql against 19c database

### ISSUE THREAD

**Issue by cs2018ncsa** [tanelpoder/tpt-oracle#6]
happy to do anything i can to help troubleshoot this. the following runs without an issue on 12.2.0.2:

SQL> @snapper ash,stats 5 1 all
Sampling SID all with interval 5 seconds, taking 1 snapshots...
    and   s.why0+s.why1+s.why2 > 0
                        *
ERROR at line 930:
ORA-06550: line 930, column 25:
PL/SQL: ORA-00904: "S"."WHY2": invalid identifier
ORA-06550: line 859, column 9:
PL/SQL: SQL Statement ignored

SQL> select * from v$version;

BANNER                                                                           BANNER_FULL                                                                                                                                                      BANNER_LEGACY                                                                        CON_ID
-------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------- ----------
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production           Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production                                                                                           Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production                    0
                                                                                 Version 19.3.0.0.0

**Comment by tanelpoder** [comment]
Did you test with the latest snapper version? An older version didn’t recognize the 19c version string.

**Comment by cs2018ncsa** [comment]
doh. latest version worked. i thought I'd cloned your repo in the last week or so but maybe not. sorry for trouble!

**Comment by tanelpoder** [comment]
No problem!

**Comment by dom-design-BDD** [comment]
Hello Tanel,
I've got the same issue as cs2018ncsa on 19c
What's the latest version of snapper.sql available compatible with 19c ? 
I'm using snapper v.4
Please advise
Best regards,

**Comment by tanelpoder** [comment]
Pull the latest snapper.sql from TPT repo, it works with 19c
